Add example with bloc.
Elementary-team/flutter-elementary pull request #43
Opened 2022-01-27 13:02 UTC by KristinaZoteva

2022-01-29 11:22 UTC, MbIXjkee requested changes
Нужны исправления

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/place_residence/place_residence_screen_widget_model.dart
> +  void updatePlaceResidence(String? newValue) {}
тело функции не нужно

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/place_residence/place_residence_screen_widget_model.dart
> +  void savePlace() {
updatePlaceInformation?

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/interests_screen/interests_screen_widget_model.dart
> +  final coordinator = context.read<IAppScope>().coordinator;
appDependencies

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/interests_screen/interests_screen_widget_model.dart
> +    super.initWidgetModel();
порядок

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/interests_screen/interests_screen_widget_model.dart
> +    _listAllInterests = model.getMockInterestsList();
это все явно через загрузку с состоянием загрузки ошибки

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/interests_screen/interests_screen.dart
> +      body: ListView.builder(
состояния загрузки/ошибки

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/about_me_screen/about_me_screen_model.dart
> +  }
отдельный метод для сохранения

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/about_me_screen/about_me_screen_model.dart
> +  void saveAboutMeInfo(String? aboutMe) {
update

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/about_me_screen/about_me_screen_widget_model.dart
> +  void onChanged(String newText) {
заприватить и в подписку контроллера

2022-01-29 11:22 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/about_me_screen/about_me_screen.dart
> +        child: EntityStateNotifierBuilder(
типизация

2022-01-31 07:24 UTC, KristinaZoteva commented on examples/profile/lib/features/profile/service/mock_server/mock_server.dart
> +import 'package:profile/features/profile/domain/mock_list_cities.dart';
+

2022-02-18 16:35 UTC, MbIXjkee requested changes

2022-02-18 16:46 UTC, MbIXjkee commented on examples/profile/lib/features/profile/screens/interests_screen/interests_screen_widget_model.dart
> +  bool isChecked(String interest) {
походу не нужный

2022-03-11 12:46 UTC, MbIXjkee requested changes

2022-03-20 15:21 UTC, MbIXjkee approved these changes
LGTM

2022-03-20 15:22 UTC, merged